---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
exclude_paths:
- config/**/*
- db/**/*
- spec/**/*
- vendor/**/*
- public/**/*
