---
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
    channel: eslint-5
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-66
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
exclude_patterns:
  - config/**/*
  - db/**/*
  - spec/**/*
  - vendor/**/*
  - public/**/*
