AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bin/**/*'

Rails:
  Enabled: true

Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

Lint/HandleExceptions:
  Exclude:
    - 'bin/**/*'
    - 'config/application.rb'
    - 'lib/tasks/*.rake'

Style/AlignParameters:
  Exclude:
    - 'bin/**/*'

Style/FileName:
  Exclude:
    - 'bin/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*.rb'
    - 'app/services/eventbrite/service.rb'

Metrics/LineLength:
  Exclude:
    - 'config/**/*.rb'
    - 'spec/rails_helper.rb'
    - 'bin/spring'
    - 'db/schema.rb'

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Style/ClassVars:
  Exclude:
    - 'spec/support/share_db_connection.rb'

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Exclude:
    - 'lib/brotherly/service.rb'
    - 'lib/tasks/test.rake'

Style/StringLiterals:
  Enabled: false
