AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bin/**/*'
    - 'bower_components/**/*'

Rails:
  Enabled: true

Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

Lint/HandleExceptions:
  Exclude:
    - 'bin/**/*'
    - 'config/application.rb'
    - 'lib/tasks/*.rake'

Style/AlignParameters:
  Exclude:
    - 'bin/**/*'

Style/FileName:
  Exclude:
    - 'bin/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*.rb'
    - 'app/services/eventbrite/service.rb'

Metrics/LineLength:
  Exclude:
    - 'config/**/*.rb'
    - 'spec/rails_helper.rb'
    - 'bin/spring'
    - 'db/schema.rb'
    - 'app/presenters/episode_presenter.rb'
    - 'spec/presenters/episode_presenter_spec.rb'
    - 'Gemfile'

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Style/ClassVars:
  Exclude:
    - 'spec/support/share_db_connection.rb'

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Exclude:
    - 'lib/brotherly/service.rb'
    - 'lib/tasks/test.rake'

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Rails/ReversibleMigration:
  Exclude:
    - 'db/migrate/20151109015541_add_audio_file_to_performances.rb'
    - 'db/migrate/20151109015634_add_audio_file_to_episodes.rb'
    - 'db/migrate/20151221195024_drop_image_id_from_artists.rb'
    - 'db/migrate/20151221195617_drop_preview_image_id_from_episodes.rb'
    - 'db/migrate/20161023050525_drop_pg_search_documents.rb'
    - 'db/migrate/20161219032731_drop_video_transcoding.rb'
