---
linters:
  BangFormat:
    enabled: false
  BorderZero:
    enabled: false
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  Comment:
    enabled: false
  DeclarationOrder:
    enabled: false
  DuplicateProperty:
    enabled: false
  ElsePlacement:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  FinalNewline:
    enabled: false
  HexLength:
    enabled: false
  HexNotation:
    enabled: false
  IdSelector:
    enabled: false
  ImportPath:
    enabled: false
  ImportantRule:
    enabled: false
  Indentation:
    enabled: false
  LeadingZero:
    enabled: false
  MergeableSelector:
    enabled: false
  NameFormat:
    enabled: false
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: false
  PropertySpelling:
    enabled: false
  PseudoElement:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  Shorthand:
    enabled: false
  SingleLinePerProperty:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  SpaceAfterComma:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: false
  SpaceAfterVariableName:
    enabled: false
  SpaceAroundOperator:
    enabled: false
  SpaceBeforeBrace:
    enabled: false
  SpaceBetweenParens:
    enabled: false
  StringQuotes:
    enabled: false
  TrailingSemicolon:
    enabled: false
  TrailingWhitespace:
    enabled: false
  UnnecessaryMantissa:
    enabled: false
  UnnecessaryParentReference:
    enabled: false
  VendorPrefix:
    enabled: false
  ZeroUnit:
    enabled: false
