scss_files: 'app/assets/stylesheets/**/*.scss'
exclude:
  - app/assets/stylesheets/videojs-sublime.scss
linters:
  Comment:
    exclude:
      - app/assets/stylesheets/application.css.scss
  EmptyRule:
    enabled: false
  Indentation:
    enabled: false
  SelectorFormat:
    enabled: false
