language: ruby
rvm: 2.6.2
before_script: bundle exec rake db:setup
cache: bundler
script: bundle exec rspec
deploy:
  - provider: heroku
    api_key:
      secure: BPfVRn6F4y+UQkpFuG/4eie29T5Rodyw6KuG6dUAqBTBzXUxWjT/takZsgHyN46FN5ldexG7MpFC2ossnkmnToIkKVT9UIjIskWqZTaB9Kg2Uynykg6S761HoBL0to0Y96ljw2BpUnQXlSZ7kNFwT59WfE06KCBULYHuLpIaBqXum97tgeNZBalvdHSxLIKy79NiDOIlJYjcGDip6b2WpBUheqipXln/mC0q2sdhZiA16YX7VlsznHgIeaJGtoen8GPByJZ5PNYyo1HunjG7q1UZVyapMVkPGPnASFR9OD5/dRqq3vNVET5zob7wq+u7SF1HpGHd2WYRwaJXSlhwt0WoDRfY4olemc/uhit8TTPg2/Ns6LdBhSWhjr2bt+T5OPO7P4gOhCqdKbRz3Fucmpe7CCbOjgMNBFelioqNHCzfosUzgRNGGuIPry/qdhzSLn2zFaAaQsgsdd+BbLMoJ37kK4csJ4ggazGgzIvib+Z5DCmIQLUs7YgevuBv82KsDytjQAPTNBAWKtdWEQwE/VEh2MvV4R+h2B9OgDzQc5OPfkmIyvOtNtTtvObrvA9MZOOIYJJ1mQOFs7NnSBWwowFc2wQ4LZzRsfdMDJmAUqiD1RhY7ERhcjgiqVcJ+HLTWdXDOpJ1yfB2QxYYgEWSA2rTnKXQaUmj3+6x8i7RrsU=
    app: brotherly
    on:
      repo: waxpoetic/brotherly
      all_branches: true
      tags: true
  - provider: heroku
    api_key:
      secure: BPfVRn6F4y+UQkpFuG/4eie29T5Rodyw6KuG6dUAqBTBzXUxWjT/takZsgHyN46FN5ldexG7MpFC2ossnkmnToIkKVT9UIjIskWqZTaB9Kg2Uynykg6S761HoBL0to0Y96ljw2BpUnQXlSZ7kNFwT59WfE06KCBULYHuLpIaBqXum97tgeNZBalvdHSxLIKy79NiDOIlJYjcGDip6b2WpBUheqipXln/mC0q2sdhZiA16YX7VlsznHgIeaJGtoen8GPByJZ5PNYyo1HunjG7q1UZVyapMVkPGPnASFR9OD5/dRqq3vNVET5zob7wq+u7SF1HpGHd2WYRwaJXSlhwt0WoDRfY4olemc/uhit8TTPg2/Ns6LdBhSWhjr2bt+T5OPO7P4gOhCqdKbRz3Fucmpe7CCbOjgMNBFelioqNHCzfosUzgRNGGuIPry/qdhzSLn2zFaAaQsgsdd+BbLMoJ37kK4csJ4ggazGgzIvib+Z5DCmIQLUs7YgevuBv82KsDytjQAPTNBAWKtdWEQwE/VEh2MvV4R+h2B9OgDzQc5OPfkmIyvOtNtTtvObrvA9MZOOIYJJ1mQOFs7NnSBWwowFc2wQ4LZzRsfdMDJmAUqiD1RhY7ERhcjgiqVcJ+HLTWdXDOpJ1yfB2QxYYgEWSA2rTnKXQaUmj3+6x8i7RrsU=
    app: brotherly-staging
    on:
      repo: waxpoetic/brotherly

addons:
  code_climate:
    repo_token:
      secure: fLGa9MDyumKmP456c6AFXcj3pi7vT8YADduUhISexe/N938HFjta1oxGb0JdN8iG/hWGEDr5lY4cvYoGsCjzR3pqkylMtKZGd0kgiSAiNEKZg3uqUa5duGcsQyT5ZJUrNjl641G1RIwFfVhwJda4JPPhMMSskvk/YWunaEbFgHgjPEagHmEcCSltdfetJ53afGAIDE85CrFThHTVeIqfRo9Zkw40vXL8YBflf9CMVNXslXSYgp8WAZ8FEKZmyzyCkB0KRv+4UOI084SNF9qqsH6RyZymk0y9BCc6uknXH2ZvXQOrZsrlF2dO+uzLa+8vg0ibW6T/q9hjxYHm1bODwjvgpQdYBQWraCbSt8ve1WjK+mh4zyQp30VwZuHPiwXgr19yEmQXn78gC6fyk5rjnKXsUNq5chanvkCeC6a75FGe3XYXNW4dleM8WEiuhRWwLjDPyN8w3+7Z5FfFDPgkeN7G46vL+o9xUnveuJ3NFUFLpur7e+aJvdB8Yj+rcN+qhHm7uohPUlXeDGM8EZWjhn+Ga1NZyQFFG/H4GoG9xCFWRxV1oaPSvi0dq4hgxtmVgNlfs9jSpBgYeI669w980UWMXQ/nJZTecT6xARV/TPH7qJY+fdYKc0nX/sOuGMNXA965vOWLXkUHv9WVBSPAidjcxj6mzktHNb+BAb7+DDo=
