language: ruby
rvm: 2.6.2
env:
  global:
    secure: Z2ttryjkg3gKr94PSwfQOBIotB2QGyB4NKBgboK2zRrRhdcrgqi1KT1Vkc2Hyn7DVuSMj7BWJBEN+98opkrgc/oqKiM5nS31pKy56f4vTxDwEmM8EiXnEi8ncazgu6fXkxf8zAjbEVcUEX4fp52MYn3Ct9ZonEcz281qOVYOShB8oaH6+YwQzUdx8mXPTLtTIN5QMhs+kzDug1t2DvJ0epMhOR5VyOnJMWtrEuvRNAhkh5pkDotcVokm82pj31uy+cfFa4LCXTU28FbV4QvJSJTvdI7CJORs5togBHiCjEMAyGPr59QjrV5lsi5anmvlF0N7/9UAhlGXMcDLEvLgCTAwGlSlEIXRaM7LFxiRuc3fJNdyxXKvQlsR+LcegoXO7/mG5zPI9wh7zLhGe1P5gret9LWxNeLHHZTRVCpnKcAkIrQnp70K7brNFO7B/mdbof22TabtgLfaMX7NxQlt3QBKy9ZGya3sbm7BjRfX5VZWI9UjuUwBkf30Xdf3vQtZLHbqW81WfmDR8F+V35VvB2RqKIITNSW6b8Up0XUuwnPo92SnkvpbIaUtNpt06swQRADCV2KoEStUnou77xyfJTZNdlH0qZ+4HrRzOND+QRZw4r+cht2xcl7Pxf/1C8fO/GScKnwC5WK2m83Rkeu+MEAO2HQSuaBEUpW7QvIOWJc=
services:
  - postgresql
cache:
  - bundler
  - yarn
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
  - bundle exec rake db:setup
  - bin/yarn install --check-files
script: bundle exec rspec
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
- provider: heroku
  api_key:
    secure: BPfVRn6F4y+UQkpFuG/4eie29T5Rodyw6KuG6dUAqBTBzXUxWjT/takZsgHyN46FN5ldexG7MpFC2ossnkmnToIkKVT9UIjIskWqZTaB9Kg2Uynykg6S761HoBL0to0Y96ljw2BpUnQXlSZ7kNFwT59WfE06KCBULYHuLpIaBqXum97tgeNZBalvdHSxLIKy79NiDOIlJYjcGDip6b2WpBUheqipXln/mC0q2sdhZiA16YX7VlsznHgIeaJGtoen8GPByJZ5PNYyo1HunjG7q1UZVyapMVkPGPnASFR9OD5/dRqq3vNVET5zob7wq+u7SF1HpGHd2WYRwaJXSlhwt0WoDRfY4olemc/uhit8TTPg2/Ns6LdBhSWhjr2bt+T5OPO7P4gOhCqdKbRz3Fucmpe7CCbOjgMNBFelioqNHCzfosUzgRNGGuIPry/qdhzSLn2zFaAaQsgsdd+BbLMoJ37kK4csJ4ggazGgzIvib+Z5DCmIQLUs7YgevuBv82KsDytjQAPTNBAWKtdWEQwE/VEh2MvV4R+h2B9OgDzQc5OPfkmIyvOtNtTtvObrvA9MZOOIYJJ1mQOFs7NnSBWwowFc2wQ4LZzRsfdMDJmAUqiD1RhY7ERhcjgiqVcJ+HLTWdXDOpJ1yfB2QxYYgEWSA2rTnKXQaUmj3+6x8i7RrsU=
  app: brotherly
  on:
    repo: waxpoetic/brotherly
    tags: true
- provider: heroku
  api_key:
    secure: BPfVRn6F4y+UQkpFuG/4eie29T5Rodyw6KuG6dUAqBTBzXUxWjT/takZsgHyN46FN5ldexG7MpFC2ossnkmnToIkKVT9UIjIskWqZTaB9Kg2Uynykg6S761HoBL0to0Y96ljw2BpUnQXlSZ7kNFwT59WfE06KCBULYHuLpIaBqXum97tgeNZBalvdHSxLIKy79NiDOIlJYjcGDip6b2WpBUheqipXln/mC0q2sdhZiA16YX7VlsznHgIeaJGtoen8GPByJZ5PNYyo1HunjG7q1UZVyapMVkPGPnASFR9OD5/dRqq3vNVET5zob7wq+u7SF1HpGHd2WYRwaJXSlhwt0WoDRfY4olemc/uhit8TTPg2/Ns6LdBhSWhjr2bt+T5OPO7P4gOhCqdKbRz3Fucmpe7CCbOjgMNBFelioqNHCzfosUzgRNGGuIPry/qdhzSLn2zFaAaQsgsdd+BbLMoJ37kK4csJ4ggazGgzIvib+Z5DCmIQLUs7YgevuBv82KsDytjQAPTNBAWKtdWEQwE/VEh2MvV4R+h2B9OgDzQc5OPfkmIyvOtNtTtvObrvA9MZOOIYJJ1mQOFs7NnSBWwowFc2wQ4LZzRsfdMDJmAUqiD1RhY7ERhcjgiqVcJ+HLTWdXDOpJ1yfB2QxYYgEWSA2rTnKXQaUmj3+6x8i7RrsU=
  app: brotherly-staging
  on:
    repo: waxpoetic/brotherly
    branch: master
