# This miniature Dockerfile lets us run Sidekiq in the app context on
# Heroku as the `worker` process.

FROM registry.heroku.com/brotherly/web:latest

CMD ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
