version: '3'
services:
  web:
    image: registry.heroku.com/brotherly/web
    build:
      context: .
      args:
        - RAILS_ENV=production
        - SECRET_KEY_BASE
  worker:
    image: registry.heroku.com/brotherly/worker
    build:
      context: .
      dockerfile: Dockerfile.worker
