
#
# Container services configuration
#

db:
  image: postgresql
  ports:
    - "5432:5432"
  volmes:
    "./config/postgresql:/etc/postgresql/conf.d"

cache:
  image: redis
  ports:
    - "6379:6379"

app:
  build: .
  command: bin/rails server --port 3000 --binding 0.0.0.0
  links:
    - db
    - cache
  ports:
    - "3000:3000"
  volumes:
    ".:/srv"

worker:
  image: app
  command: bin/sidekiq --config config/sidekiq.yml
  links:
    - db
    - cache

web:
  image: nginx
  links:
    - app
  ports:
    - "80:80"
  volumes:
    "./config/nginx:/etc/nginx/conf.d"
