default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: brotherly_development
  host: db

test:
  <<: *default
  database: brotherly_test
  host: db

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["MAX_THREADS"] %>
