default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: brotherly_development

test:
  <<: *default
  database: brotherly_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
