default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: brotherly_development

test:
  <<: *default
  database: brotherly_test

production:
  <<: *default
  database: brotherly_production
  username: brotherly
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
