development:
  secret_key_base: 73e29df01f4db4384a6cded4fa245639dff374a22759af9ee65866e28ca33dc03317f1caf9a6ac97fee80fa3822921eda9595c0396d2ceac387cddda5a0461bf
  eventbrite_api_key: 'test'
  eventbrite_client_secret: 'secret'
  eventbrite_auth_token: 'token'
  aws_region: us-east-1
  aws_s3_bucket_name: files.brother.ly
  aws_access_key_id: 'AKIA12345'
  aws_secret_access_key: <%= SecureRandom.hex %>
  aws_transcoder_pipeline_id: '23498209348092384-42j3lk'
  redis_url: redis://localhost:6379
  admin_email: 'admin@example.com'
  admin_password: 'password123'
  sendgrid_username: 'test@example.com'
  sendgrid_password: 'password1'
  airbrake_api_key: '12345'
  google_analytics_code:
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  bitly_api_key: '33dc3b8a187907eaf5643592a173ca36d910ac90'
  domain_name: brotherly.dev

test:
  secret_key_base: 171357b559b7c0ce65ed02cec1705da38e1fe5cc15572f8b9cd33acaf730b31161f3856ae69c84ceb6de3208a1d9f8b24831eafebf91609b6f37ba317e712fc5
  eventbrite_api_key: 'test'
  eventbrite_client_secret: 'secret'
  eventbrite_auth_token: 'token'
  aws_region: us-east-1
  aws_access_key_id: 'AKIA12345'
  aws_secret_access_key: <%= SecureRandom.hex %>
  aws_s3_bucket_name: files.brother.ly
  aws_transcoder_pipeline_id: '23498209348092384-42j3lk'
  redis_url: redis://localhost:6379
  admin_email: 'admin@example.com'
  admin_password: 'password123'
  sendgrid_username: 'test@example.com'
  sendgrid_password: 'password1'
  airbrake_api_key: '12345'
  google_analytics_code:
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  bitly_api_key: '33dc3b8a187907eaf5643592a173ca36d910ac90'
  domain_name: brotherly.dev

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  eventbrite_api_key: <%= ENV["EVENTBRITE_API_KEY"] %>
  eventbrite_client_secret: <%= ENV["EVENTBRITE_CLIENT_SECRET"] %>
  eventbrite_auth_token: <%= ENV["EVENTBRITE_AUTH_TOKEN"] %>
  aws_region: us-east-1
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_audio_pipeline_id: <%= ENV["AWS_AUDIO_PIPELINE_ID"] %>
  aws_video_pipeline_id: <%= ENV["AWS_VIDEO_PIPELINE_ID"] %>
  cdn_domain_name: <%= ENV['CDN_DOMAIN_NAME'] %>
  redis_url: <%= ENV["REDIS_URL"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  airbrake_api_key: <%= ENV["AIRBRAKE_API_KEY"] %>
  airbrake_project_id: <%= ENV["AIRBRAKE_PROJECT_ID"] %>
  google_analytics_code: <%= ENV['GOOGLE_ANALYTICS_CODE'] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  google_tag_manager_id: <%= ENV['GOOGLE_TAG_MANAGER_ID'] %>
  pingdom_rum_id: <%= ENV['PINGDOM_RUM_ID'] %>
  facebook_admin_id: <%= ENV["FACEBOOK_ADMIN_ID"] %>
  bitly_api_key: <%= ENV["BITLY_API_KEY"] %>
  aws_transcoder_pipeline_id: <%= ENV["AWS_TRANSCODER_PIPELINE_ID"] %>
  domain_name: <%= ENV['DOMAIN_NAME'] %>
  new_relic_app_name: <%= ENV['NEW_RELIC_APP_NAME'] %>
