development:
  secret_key_base: 73e29df01f4db4384a6cded4fa245639dff374a22759af9ee65866e28ca33dc03317f1caf9a6ac97fee80fa3822921eda9595c0396d2ceac387cddda5a0461bf
  eventbrite_api_key: 'test'
  eventbrite_client_secret: 'secret'
  eventbrite_auth_token: 'token'
  aws_region: us-east-1
  aws_s3_bucket_name: files.brother.ly
  aws_access_key_id: 'AKIA12345'
  aws_secret_access_key: <%= SecureRandom.hex %>
  aws_cloudfront_distro_id: <%= SecureRandom.random_number %>
  aws_audio_pipeline_id: <%= ENV["AWS_AUDIO_PIPELINE_ID"] %>
  aws_video_pipeline_id: <%= ENV["AWS_VIDEO_PIPELINE_ID"] %>
  redis_host: localhost
  admin_email: 'admin@example.com'
  admin_password: 'password123'

test:
  secret_key_base: 171357b559b7c0ce65ed02cec1705da38e1fe5cc15572f8b9cd33acaf730b31161f3856ae69c84ceb6de3208a1d9f8b24831eafebf91609b6f37ba317e712fc5
  eventbrite_api_key: 'test'
  eventbrite_client_secret: 'secret'
  eventbrite_auth_token: 'token'
  aws_region: us-east-1
  aws_access_key_id: 'AKIA12345'
  aws_secret_access_key: <%= SecureRandom.hex %>
  aws_s3_bucket_name: files.brother.ly
  aws_cloudfront_distro_id: <%= SecureRandom.random_number %>
  aws_audio_pipeline_id: <%= ENV["AWS_AUDIO_PIPELINE_ID"] %>
  aws_video_pipeline_id: <%= ENV["AWS_VIDEO_PIPELINE_ID"] %>
  redis_host: localhost
  admin_email: 'admin@example.com'
  admin_password: 'password123'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  eventbrite_api_key: <%= ENV["EVENTBRITE_API_KEY"] %>
  eventbrite_client_secret: <%= ENV["EVENTBRITE_CLIENT_SECRET"] %>
  eventbrite_auth_token: <%= ENV["EVENTBRITE_AUTH_TOKEN"] %>
  aws_region: us-east-1
  aws_s3_bucket_name: files.brother.ly
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_cloudfront_distro_id: <%= ENV["AWS_CLOUDFRONT_DISTRO_ID"] %>
  aws_audio_pipeline_id: <%= ENV["AWS_AUDIO_PIPELINE_ID"] %>
  aws_video_pipeline_id: <%= ENV["AWS_VIDEO_PIPELINE_ID"] %>
  redis_host: redis
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  fog_directory: <%= ENV["FOG_DIRECTORY"] %>
