development:
  secret_key_base: 73e29df01f4db4384a6cded4fa245639dff374a22759af9ee65866e28ca33dc03317f1caf9a6ac97fee80fa3822921eda9595c0396d2ceac387cddda5a0461bf
  eventbrite_api_key: 'test'
  eventbrite_client_secret: 'secret'
  eventbrite_auth_token: 'token'

test:
  secret_key_base: 171357b559b7c0ce65ed02cec1705da38e1fe5cc15572f8b9cd33acaf730b31161f3856ae69c84ceb6de3208a1d9f8b24831eafebf91609b6f37ba317e712fc5
  eventbrite_api_key: 'test'
  eventbrite_client_secret: 'secret'
  eventbrite_auth_token: 'token'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  eventbrite_api_key: <%= ENV["EVENTBRITE_API_KEY"] %>
  eventbrite_client_secret: <%= ENV["EVENTBRITE_CLIENT_SECRET"] %>
  eventbrite_auth_token: <%= ENV["EVENTBRITE_AUTH_TOKEN"] %>

